In [3]:
# 일단 import 
%matplotlib inline  

import matplotlib as mpl  # 기본 설정 만지는 용도
import matplotlib.pyplot as plt  # 그래프 그리는 용도
import matplotlib.font_manager as fm  # 폰트 관련 용도


print(mpl.__version__)
print(mpl.__file__)
print(mpl.get_configdir())
print(mpl.get_cachedir())

sys_font=fm.findSystemFonts()
print(f"sys_font number: {len(sys_font)}")
print(sys_font)

nanum_font = [f for f in sys_font if 'Nanum' in f]
print(f"nanum_font number: {len(nanum_font)}")

!apt-get update -qq
!apt-get install fonts-nanum* -qq


# 체크해보면 폰트 개수가 늘어났다
sys_font=fm.findSystemFonts()
print(f"sys_font number: {len(sys_font)}")

nanum_font = [f for f in sys_font if 'Nanum' in f]
print(f"nanum_font number: {len(nanum_font)}")


# 현재 설정되어 있는 폰트 사이즈와 글꼴을 알아보자
!python --version
def current_font():
  print(f"설정 폰트 글꼴: {plt.rcParams['font.family']}, 설정 폰트 사이즈: {plt.rcParams['font.size']}")  # 파이썬 3.6 이상 사용가능하다
        
current_font()

path = '/usr/share/fonts/truetype/nanum/NanumGothicEco.ttf'  # 설치된 나눔글꼴중 원하는 녀석의 전체 경로를 가져오자
font_name = fm.FontProperties(fname=path, size=10).get_name()
print(font_name)
plt.rc('font', family=font_name)

# 우선 fm._rebuild() 를 해주고
fm._rebuild()

mpl.rcParams['axes.unicode_minus'] = False

3.2.2
/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py
/root/.config/matplotlib
/root/.cache/matplotlib
sys_font number: 17
['/usr/share/fonts/truetype/liberation/LiberationMono-Italic.ttf', '/usr/share/fonts/truetype/liberation/LiberationMono-BoldItalic.ttf', '/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Italic.ttf', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf', '/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf', '/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf', '/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Bold.ttf', '/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Regular.ttf', '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf', '/usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf', '/usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf', '/usr/share/fonts/truetype/humor-sans/Humor-

In [15]:
import sys 
assert sys.version_info >= (3, 5)

import sklearn
assert sklearn.__version__ >= "0.20"

try:
  %tensorflow_version 2.x
except Exception:
  pass  

import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"

import numpy as np
import os

import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

PROJECT_ROOT_DIR = "."
CHAPTER_ID = "deep"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
  path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
  print("Saving figure", fig_id)
  if tight_layout:
    plt.tight_layout()
  plt.savefig(path, format=fig_extension, dpi=resolution)


In [17]:
keras.layers.Dense(10, activation="relu", kernel_initializer="he_normal")

In [18]:
he_avg_init = keras.initializers.VarianceScaling(scale=2., mode="fan_avg", distribution="uniform")

keras.layers.Dense(10, activation="sigmoid", kernel_initializer=he_avg_init)

11.1.2 수렴하지 않는 활성화 함수

In [19]:
model = keras.models.Sequential(
    [
     keras.layers.Flatten(input_shape=[28, 28]),
     keras.layers.Dense(300, kernel_initializer="he_normal"),
     keras.layers.LeakyReLU(alpha=0.2),
     keras.layers.Dense(100, kernel_initializer="he_normal"),
     keras.layers.LeakyReLU(alpha=0.2),
     keras.layers.Dense(10, activation="softmax")
    ]
)

In [20]:
layer = keras.layers.Dense(10, activation="selu", kernel_initializer="lecun_normal")

11.1.3 배치 정규화

In [21]:
model = keras.models.Sequential(
    [
     keras.layers.Flatten(input_shape=[28, 28]),
     keras.layers.BatchNormalization(),
     keras.layers.Dense(300, activation="elu", kernel_initializer="he_normal"),
     keras.layers.BatchNormalization(),
     keras.layers.Dense(100, activation="elu", kernel_initializer="he_normal"),
     keras.layers.BatchNormalization(),
     keras.layers.Dense(10, activation="softmax")
    ]
)


In [22]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
batch_normalization_3 (Batch (None, 784)               3136      
_________________________________________________________________
dense_15 (Dense)             (None, 300)               235500    
_________________________________________________________________
batch_normalization_4 (Batch (None, 300)               1200      
_________________________________________________________________
dense_16 (Dense)             (None, 100)               30100     
_________________________________________________________________
batch_normalization_5 (Batch (None, 100)               400       
_________________________________________________________________
dense_17 (Dense)             (None, 10)               

In [27]:
[
 (var.name, var.trainable) for var in model.layers[1].variables
]

[('batch_normalization_3/gamma:0', True),
 ('batch_normalization_3/beta:0', True),
 ('batch_normalization_3/moving_mean:0', False),
 ('batch_normalization_3/moving_variance:0', False)]

In [29]:
model.layers[1].updates

[]

In [33]:
(X_train_full, y_train_full), (X_test, y_test) = keras.datasets.fashion_mnist.load_data()
X_train_full = X_train_full / 255.0
X_test = X_test / 255.0
X_valid, X_train = X_train_full[:5000], X_train_full[5000:]
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]

In [35]:
tf.random.set_seed(42)
np.random.seed(42)

model = keras.models.Sequential(
    [
     keras.layers.Flatten(input_shape=[28,28]),
     keras.layers.BatchNormalization(),
     keras.layers.Dense(300, kernel_initializer="he_normal", use_bias=False),
     keras.layers.BatchNormalization(),
     keras.layers.Activation('elu'),
     keras.layers.Dense(100, kernel_initializer="he_normal", use_bias=False),
     keras.layers.BatchNormalization(),
     keras.layers.Activation('elu'),
     keras.layers.Dense(10, activation="softmax")
    ]
)

In [43]:
model.compile(loss="sparse_categorical_crossentropy", optimizer=keras.optimizers.SGD(lr=1e-3), metrics=["accuracy"])


def leaky_relu(z, alpha=0.01):
    return np.maximum(alpha*z, z)

In [48]:
history = model.fit(
    X_train, y_train, epochs=10, validation_data=(X_valid, y_valid)
)


Epoch 1/10
1719/1719 [==============================] - 8s 5ms/step - loss: 27.6133 - val_loss: 27.5906
Epoch 2/10
1719/1719 [==============================] - 8s 5ms/step - loss: 27.6132 - val_loss: 27.5905
Epoch 3/10
1719/1719 [==============================] - 8s 5ms/step - loss: 27.6131 - val_loss: 27.5904
Epoch 4/10
1719/1719 [==============================] - 8s 5ms/step - loss: 27.6129 - val_loss: 27.5903
Epoch 5/10
1719/1719 [==============================] - 8s 5ms/step - loss: 27.6129 - val_loss: 27.5902
Epoch 6/10
1719/1719 [==============================] - 8s 5ms/step - loss: 27.6129 - val_loss: 27.5902
Epoch 7/10
1719/1719 [==============================] - 8s 5ms/step - loss: 27.6128 - val_loss: 27.5901
Epoch 8/10
1719/1719 [==============================] - 9s 5ms/step - loss: 27.6128 - val_loss: 27.5901
Epoch 9/10
1719/1719 [==============================] - 9s 5ms/step - loss: 27.6127 - val_loss: 27.5900
Epoch 10/10
1719/1719 [==============================] - 8s 5ms/

11.1.4 그레이디언트 클리핑

In [50]:
def split_dataset(X, y):
  y_5_or_6 = (y == 5) | (y == 6)
  y_A = y[~y_5_or_6]
  y_A[y_A > 6] -= 2
  y_B = (y[y_5_or_6] == 5).astype(np.float32)
  return (
      (X[~y_5_or_6], y_A),
      (X[y_5_or_6], y_B)
  )

(X_train_A, y_train_A), (X_train_B, y_train_B) = split_dataset(X_train, y_train)
(X_train_B, y_train_B), (X_train_B, y_train_B) = split_dataset(X_train, y_train)
(X_test_A, y_test_A), (X_test_B, y_test_B) = split_dataset(X_test, y_test)
X_train_B = X_train_B[:200]
y_train_B = y_train_B[:200]

In [64]:
X_train_A.shape

(43986, 28, 28)

In [52]:
X_train_B.shape

(200, 28, 28)

In [53]:
y_train_A[:30]

array([4, 0, 5, 7, 7, 7, 4, 4, 3, 4, 0, 1, 6, 3, 4, 3, 2, 6, 5, 3, 4, 5,
       1, 3, 4, 2, 0, 6, 7, 1], dtype=uint8)

In [54]:
y_train_B[:30]

array([0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [55]:
tf.random.set_seed(42)
np.random.seed(42)

In [72]:
model_A.compile(loss="sparse_categorical_crossentropy",
                optimizer=keras.optimizers.SGD(lr=1e-3),
                metrics=["accuracy"])

In [73]:
history = model_A.fit(X_train_A, y_train_A, epochs=20,
                    validation_data=(X_valid, y_valid))

Epoch 1/20
1375/1375 [==============================] - 2s 1ms/step - loss: 21.3577 - accuracy: 0.0000e+00 - val_loss: 21.1000 - val_accuracy: 0.0000e+00
Epoch 2/20
1375/1375 [==============================] - 2s 2ms/step - loss: 21.3577 - accuracy: 0.0000e+00 - val_loss: 21.1000 - val_accuracy: 0.0000e+00
Epoch 3/20
1375/1375 [==============================] - 2s 2ms/step - loss: 21.3577 - accuracy: 0.0000e+00 - val_loss: 21.1000 - val_accuracy: 0.0000e+00
Epoch 4/20
1375/1375 [==============================] - 2s 2ms/step - loss: 21.3577 - accuracy: 0.0000e+00 - val_loss: 21.1000 - val_accuracy: 0.0000e+00
Epoch 5/20
1375/1375 [==============================] - 2s 2ms/step - loss: 21.3577 - accuracy: 0.0000e+00 - val_loss: 21.1000 - val_accuracy: 0.0000e+00
Epoch 6/20
1375/1375 [==============================] - 2s 2ms/step - loss: 21.3577 - accuracy: 0.0000e+00 - val_loss: 21.1000 - val_accuracy: 0.0000e+00
Epoch 7/20
1375/1375 [==============================] - 2s 2ms/step - loss: 

In [74]:
model_A.save("my_model_A.h5")

In [75]:
optimizer = keras.optimizers.SGD(
    clipvalue=1.0
)

model.compile(loss="mse", optimizer=optimizer)

11.2.1 케라스를 사용한 전이 학습

In [76]:
model_A = keras.models.load_model("my_model_A.h5")
model_B_on_A = keras.models.Sequential(model_A.layers[:-1])
model_B_on_A.add(keras.layers.Dense(1, activation="sigmoid"))

In [77]:
model_A_clone = keras.models.clone_model(model_A)
model_A_clone.set_weights(model_A.get_weights())

In [78]:
for layer in model_B_on_A.layers[:-1]:
  layer.trainable = False

model_B_on_A.compile(loss="binary_crossentropy", optimizer="sgd", metrics=["accuracy"])

In [80]:
history = model_B_on_A.fit(
    X_train_B, y_train_B, epochs=4,
    validation_data=(X_valid, y_valid)
)


Epoch 1/4
7/7 [==============================] - 0s 46ms/step - loss: 0.6637 - accuracy: 0.6370 - val_loss: 1.5672 - val_accuracy: 0.0893
Epoch 2/4
7/7 [==============================] - 0s 22ms/step - loss: 0.6574 - accuracy: 0.7277 - val_loss: 1.6449 - val_accuracy: 0.0894
Epoch 3/4
7/7 [==============================] - 0s 24ms/step - loss: 0.6525 - accuracy: 0.7345 - val_loss: 1.7238 - val_accuracy: 0.0894
Epoch 4/4
7/7 [==============================] - 0s 23ms/step - loss: 0.6476 - accuracy: 0.7395 - val_loss: 1.8084 - val_accuracy: 0.0895


In [81]:
for layer in model_B_on_A.layers[:-1]:
  layer.trainable = True

optimizer = keras.optimizers.SGD(lr=1e-4) 
model_B_on_A.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

history = model_B_on_A.fit(
    X_train_B, y_train_B, epochs=16, validation_data=(X_valid, y_valid)
)

Epoch 1/16
7/7 [==============================] - 0s 39ms/step - loss: 0.6445 - accuracy: 0.7434 - val_loss: 1.8093 - val_accuracy: 0.0895
Epoch 2/16
7/7 [==============================] - 0s 23ms/step - loss: 0.6444 - accuracy: 0.7434 - val_loss: 1.8099 - val_accuracy: 0.0895
Epoch 3/16
7/7 [==============================] - 0s 21ms/step - loss: 0.6444 - accuracy: 0.7434 - val_loss: 1.8106 - val_accuracy: 0.0895
Epoch 4/16
7/7 [==============================] - 0s 21ms/step - loss: 0.6443 - accuracy: 0.7434 - val_loss: 1.8114 - val_accuracy: 0.0895
Epoch 5/16
7/7 [==============================] - 0s 23ms/step - loss: 0.6443 - accuracy: 0.7436 - val_loss: 1.8122 - val_accuracy: 0.0895
Epoch 6/16
7/7 [==============================] - 0s 22ms/step - loss: 0.6442 - accuracy: 0.7436 - val_loss: 1.8130 - val_accuracy: 0.0895
Epoch 7/16
7/7 [==============================] - 0s 22ms/step - loss: 0.6442 - accuracy: 0.7436 - val_loss: 1.8138 - val_accuracy: 0.0895
Epoch 8/16
7/7 [===========

In [82]:
model_B_on_A.evaluate(X_test_B, y_test_B)

63/63 [==============================] - 0s 1ms/step - loss: 0.6448 - accuracy: 0.7339


[0.6448253989219666, 0.7339106798171997]

11.3.1 모멘텀 최적화

In [83]:
optimizer = keras.optimizers.SGD(lr=0.001, momentum=0.9)

11.3.2 네스테로프 가속 경사

11.3.4 RMSProp

In [84]:
optimizer = keras.optimizers.RMSprop(lr=0.001, rho=0.9)

11.3.5 Adam과 Nadam 최적화

In [85]:
optimizer = keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999)

11.3.6 학습률 스케줄링

In [86]:
optimizer = keras.optimizers.SGD(lr=0.01, decay=1e-4)

In [87]:
def exponential_decay_fn(epoch):
  return 0.01 * 0.1**(epoch / 20)

In [88]:
def exponential_decay(lr0, s):
  def exponential_decay_fn(epoch):
    return lr0 * 0.1**(epoch / s)
  return exponential_decay_fn

exponential_decay_fn = exponential_decay(lr0=0.01, s=20)

In [89]:

pixel_means = X_train.mean(axis=0, keepdims=True)
pixel_stds = X_train.std(axis=0, keepdims=True)
X_train_scaled = (X_train - pixel_means) / pixel_stds
X_valid_scaled = (X_valid - pixel_means) / pixel_stds
X_test_scaled = (X_test - pixel_means) / pixel_stds

In [90]:
lr_scheduler = keras.callbacks.LearningRateScheduler(exponential_decay_fn)
history = model.fit(
    X_train_scaled, y_train, epochs=25, validation_data=(X_valid_scaled, y_valid), 
    callbacks=[lr_scheduler]
)

Epoch 1/25
1719/1719 [==============================] - 12s 7ms/step - loss: 27.6127 - val_loss: 27.5900
Epoch 2/25
1719/1719 [==============================] - 11s 6ms/step - loss: 27.6127 - val_loss: 27.5900
Epoch 3/25
1719/1719 [==============================] - 11s 6ms/step - loss: 27.6127 - val_loss: 27.5900
Epoch 4/25
1719/1719 [==============================] - 11s 6ms/step - loss: 27.6126 - val_loss: 27.5900
Epoch 5/25
1719/1719 [==============================] - 11s 6ms/step - loss: 27.6126 - val_loss: 27.5899
Epoch 6/25
1719/1719 [==============================] - 12s 7ms/step - loss: 27.6126 - val_loss: 27.5899
Epoch 7/25
1719/1719 [==============================] - 11s 6ms/step - loss: 27.6126 - val_loss: 27.5899
Epoch 8/25
1719/1719 [==============================] - 11s 6ms/step - loss: 27.6125 - val_loss: 27.5899
Epoch 9/25
1719/1719 [==============================] - 11s 7ms/step - loss: 27.6125 - val_loss: 27.5899
Epoch 10/25
1719/1719 [==============================] 

In [91]:
def exponential_decay_fn(epoch, lr):
  return lr * 0.1**(1 / 20)

def piecewise_constant_fn(epoch):
  if epoch < 5:
    return 0.01
  elif epoch < 15:
    return 0.005
  else:
    return 0.001


In [92]:
lr_scheduler = keras.callbacks.ReduceLROnPlateau(factor=0.5, patience=5)

In [94]:
s = 20 * len(X_train) // 32
learning_rate = keras.optimizers.schedules.ExponentialDecay(0.01, s, 0.1)
optimizer = keras.optimizers.SGD(learning_rate)

11.4 과대적합 피하기

In [95]:
layer = keras.layers.Dense(
    100, activation="elu", kernel_initializer="he_normal", kernel_regularizer=keras.regularizers.l2(0.01)
)

In [96]:
from functools import partial

RegularizedDense = partial(
    keras.layers.Dense,
    activation="elu",
    kernel_initializer="he_normal",
    kernel_regularizer=keras.regularizers.l2(0.01)
)

model = keras.models.Sequential(
    [
     keras.layers.Flatten(input_shape=[28, 28]),
     RegularizedDense(300),
     RegularizedDense(100),
     RegularizedDense(10, activation="softmax", kernel_initializer="glorot_uniform"),
    ]
)

11.4.2 드롭아웃

In [97]:
model = keras.models.Sequential(
    [
     keras.layers.Flatten(input_shape=[28, 28]),
     keras.layers.Dropout(rate=0.2),
     keras.layers.Dense(300, activation="elu", kernel_initializer="he_normal"),
     keras.layers.Dropout(rate=0.2),
     keras.layers.Dense(100, activation="elu", kernel_initializer="he_normal"),
     keras.layers.Dropout(rate=0.2),
     keras.layers.Dense(10, activation="softmax")
    ]
)

11.4.3 몬테 카를로 드롭아웃

In [99]:
y_probas = np.stack(
    [
     model(X_test_scaled, training=True) for sample in range(100)
    ]
)

y_proba = y_probas.mean(axis=0)

In [100]:
np.round(model.predict(X_test_scaled[:1]), 2)

array([[0.4 , 0.04, 0.18, 0.03, 0.03, 0.01, 0.07, 0.11, 0.04, 0.09]],
      dtype=float32)

In [101]:
np.round(y_probas[:, :1], 2)

array([[[0.22, 0.  , 0.12, 0.03, 0.02, 0.04, 0.03, 0.05, 0.03, 0.44]],

       [[0.32, 0.05, 0.09, 0.  , 0.14, 0.01, 0.24, 0.04, 0.  , 0.1 ]],

       [[0.12, 0.06, 0.36, 0.02, 0.  , 0.  , 0.06, 0.03, 0.03, 0.31]],

       [[0.38, 0.03, 0.27, 0.01, 0.01, 0.  , 0.03, 0.19, 0.03, 0.05]],

       [[0.26, 0.03, 0.02, 0.07, 0.07, 0.01, 0.26, 0.06, 0.09, 0.13]],

       [[0.65, 0.  , 0.06, 0.1 , 0.  , 0.01, 0.01, 0.05, 0.07, 0.06]],

       [[0.23, 0.32, 0.16, 0.  , 0.02, 0.  , 0.14, 0.06, 0.04, 0.03]],

       [[0.05, 0.04, 0.13, 0.01, 0.  , 0.01, 0.56, 0.09, 0.04, 0.08]],

       [[0.07, 0.29, 0.25, 0.01, 0.12, 0.  , 0.01, 0.06, 0.07, 0.11]],

       [[0.2 , 0.12, 0.2 , 0.01, 0.  , 0.  , 0.01, 0.1 , 0.01, 0.35]],

       [[0.02, 0.08, 0.23, 0.06, 0.17, 0.01, 0.23, 0.06, 0.04, 0.09]],

       [[0.29, 0.14, 0.2 , 0.03, 0.03, 0.09, 0.03, 0.01, 0.01, 0.18]],

       [[0.41, 0.05, 0.13, 0.01, 0.13, 0.  , 0.05, 0.08, 0.  , 0.14]],

       [[0.31, 0.16, 0.28, 0.  , 0.01, 0.  , 0.04, 0.02, 0.  , 0

In [102]:
np.round(y_proba[:1], 2)

array([[0.33, 0.09, 0.15, 0.04, 0.06, 0.01, 0.07, 0.1 , 0.05, 0.11]],
      dtype=float32)

In [103]:
y_std = y_probas.std(axis=0)

In [104]:
np.round(y_std[:1], 2)

array([[0.27, 0.12, 0.16, 0.06, 0.11, 0.02, 0.1 , 0.13, 0.09, 0.13]],
      dtype=float32)

In [106]:
y_pred = np.argmax(y_proba, axis=1)

In [107]:
accuracy = np.sum(y_pred == y_test) / len(y_test)

In [108]:
accuracy

0.1339

In [109]:
class MCDropout(keras.layers.Dropout):
  def call(self, inputs):
    return super().call(inputs, training=True)

11.4.4 맥스-노름 규제

In [110]:
keras.layers.Dense(
    100, activation="elu", kernel_initializer="he_normal", kernel_constraint=keras.constraints.max_norm(1.)
)