In [ ]:
# 일단 import 
%matplotlib inline  

import matplotlib as mpl  # 기본 설정 만지는 용도
import matplotlib.pyplot as plt  # 그래프 그리는 용도
import matplotlib.font_manager as fm  # 폰트 관련 용도


print(mpl.__version__)
print(mpl.__file__)
print(mpl.get_configdir())
print(mpl.get_cachedir())

sys_font=fm.findSystemFonts()
print(f"sys_font number: {len(sys_font)}")
print(sys_font)

nanum_font = [f for f in sys_font if 'Nanum' in f]
print(f"nanum_font number: {len(nanum_font)}")

!apt-get update -qq
!apt-get install fonts-nanum* -qq


# 체크해보면 폰트 개수가 늘어났다
sys_font=fm.findSystemFonts()
print(f"sys_font number: {len(sys_font)}")

nanum_font = [f for f in sys_font if 'Nanum' in f]
print(f"nanum_font number: {len(nanum_font)}")


# 현재 설정되어 있는 폰트 사이즈와 글꼴을 알아보자
!python --version
def current_font():
  print(f"설정 폰트 글꼴: {plt.rcParams['font.family']}, 설정 폰트 사이즈: {plt.rcParams['font.size']}")  # 파이썬 3.6 이상 사용가능하다
        
current_font()

path = '/usr/share/fonts/truetype/nanum/NanumGothicEco.ttf'  # 설치된 나눔글꼴중 원하는 녀석의 전체 경로를 가져오자
font_name = fm.FontProperties(fname=path, size=10).get_name()
print(font_name)
plt.rc('font', family=font_name)

# 우선 fm._rebuild() 를 해주고
fm._rebuild()

mpl.rcParams['axes.unicode_minus'] = False

3.2.2
/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py
/root/.config/matplotlib
/root/.cache/matplotlib
sys_font number: 17
['/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf', '/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf', '/usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf', '/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Bold.ttf', '/usr/share/fonts/truetype/liberation/LiberationMono-BoldItalic.ttf', '/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf', '/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Italic.ttf', '/usr/share/fonts/truetype/liberation/LiberationMono-Italic.ttf', '/usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf', '/usr/share/fonts/truetype/liberation/LiberationSerif-BoldItalic.ttf', '/usr/share/fonts/truetype/liberation/LiberationSansNarrow-BoldItalic.ttf', '/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf', '/usr/share/fonts/truetype/liberati

In [ ]:
import sys
assert sys.version_info >= (3, 5)

import sklearn
assert sklearn.__version__ >= "0.20"

try:
  !pip install -a -U tfx==0.21.2
  print('error')
except Exception:
  pass

import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"

import numpy as np
import os

np.random.seed(42)

%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc("axes", labelsize=14)
mpl.rc("xtick", labelsize=12)
mpl.rc("ytick", labelsize=12)

PROJECT_ROOT_DIR = "."
CHAPTER_ID = "data"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
  path= os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
  print("save figure", fig_id)
  if tight_layout:
    plt.tight_layout()
  plt.savefig(path, format=fig_extension, dpi=resolution)
  



Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: -a
error


In [ ]:
X = tf.range(10) #샘플 데이터 텐서
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [ ]:
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


13.1.1 연쇄 변환

In [ ]:
dataset = dataset.repeat(3).batch(7)

In [ ]:
for item in dataset:
  print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [ ]:
dataset = dataset.map(lambda x: x * 2) # 아이템 [0,2,4,6,8,10,12]

In [ ]:
for item in dataset:
  print(item)

tf.Tensor([ 0  2  4  6  8 10 12], shape=(7,), dtype=int32)
tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)
tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)
tf.Tensor([16 18], shape=(2,), dtype=int32)


In [ ]:
dataset = dataset.apply(tf.data.experimental.unbatch()) #아이템 : 0,2,4.....

Instructions for updating:
Use `tf.data.Dataset.unbatch()`.


In [ ]:
dataset = dataset.filter(lambda x: x < 10) #아이템: 0 2 4 6 8 0 2 4 6 ...

In [ ]:
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


13.1.2 데이터 셔플링

In [ ]:
dataset = tf.data.Dataset.range(10).repeat(3) # 0에서 9까지 3번 반복
dataset = dataset.shuffle(buffer_size=5, seed=42).batch(7)


In [ ]:
for item in dataset:
  print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 9], shape=(7,), dtype=int64)
tf.Tensor([3 6], shape=(2,), dtype=int64)


In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()
x_train_full, x_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target.reshape(-1, 1), random_state=42
)

x_train, x_valid, y_train, y_valid = train_test_split(
    x_train_full, y_train_full, random_state=42
)

scaler = StandardScaler()
scaler.fit(x_train)
x_mean = scaler.mean_
x_std = scaler.scale_

In [ ]:
def save_to_multiple_csv_files(data, name_prefix, header=None, n_parts=10):
  housing_dir = os.path.join("datasets", "housing")
  os.makedirs(housing_dir, exist_ok=True)
  path_format = os.path.join(housing_dir, "my_{}_{:02d}.csv")

  filepaths = []
  m = len(data)
  for file_idx, row_indices in enumerate(np.array_split(np.arange(m), n_parts)):
    part_csv = path_format.format(name_prefix, file_idx)
    filepaths.append(part_csv)
    with open(part_csv, "wt", encoding="utf-8") as f:
      if header is not None:
        f.write(header)
        f.write("\n")
      for row_idx in row_indices:
        f.write(",".join(
            [repr(col) for col in data[row_idx]]
        ))
        f.write("\n")
  return filepaths

In [ ]:
train_data = np.c_[x_train, y_train]
valid_data = np.c_[x_valid, y_valid]
test_data = np.c_[x_test, y_test]
header_cols = housing.feature_names + ["MedianHouseValue"]
header = ",".join(header_cols)



In [ ]:
train_filepaths = save_to_multiple_csv_files(train_data, "train", header, n_parts=20)
valid_filepaths = save_to_multiple_csv_files(valid_data, "valid", header, n_parts=10)
test_filepaths = save_to_multiple_csv_files(test_data, "test", header, n_parts=10)

In [ ]:
import pandas as pd
pd.read_csv( train_filepaths[0] ).head()

MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  MedianHouseValue
0  3.5214      15.0  3.049945  ...     37.63    -122.43             1.442
1  5.3275       5.0  6.490060  ...     33.69    -117.39             1.687
2  3.1000      29.0  7.542373  ...     38.44    -122.98             1.621
3  7.1736      12.0  6.289003  ...     33.55    -117.70             2.621
4  2.0549      13.0  5.312457  ...     33.93    -116.93             0.956

[5 rows x 9 columns]

In [ ]:
with open(train_filepaths[0]) as f:
  for i in range(5):
    print(f.readline(), end="")

MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedianHouseValue
3.5214,15.0,3.0499445061043287,1.106548279689234,1447.0,1.6059933407325193,37.63,-122.43,1.442
5.3275,5.0,6.490059642147117,0.9910536779324056,3464.0,3.4433399602385686,33.69,-117.39,1.687
3.1,29.0,7.5423728813559325,1.5915254237288134,1328.0,2.2508474576271187,38.44,-122.98,1.621
7.1736,12.0,6.289002557544757,0.9974424552429667,1054.0,2.6956521739130435,33.55,-117.7,2.621


In [ ]:
train_filepaths

['datasets/housing/my_train_00.csv',
 'datasets/housing/my_train_01.csv',
 'datasets/housing/my_train_02.csv',
 'datasets/housing/my_train_03.csv',
 'datasets/housing/my_train_04.csv',
 'datasets/housing/my_train_05.csv',
 'datasets/housing/my_train_06.csv',
 'datasets/housing/my_train_07.csv',
 'datasets/housing/my_train_08.csv',
 'datasets/housing/my_train_09.csv',
 'datasets/housing/my_train_10.csv',
 'datasets/housing/my_train_11.csv',
 'datasets/housing/my_train_12.csv',
 'datasets/housing/my_train_13.csv',
 'datasets/housing/my_train_14.csv',
 'datasets/housing/my_train_15.csv',
 'datasets/housing/my_train_16.csv',
 'datasets/housing/my_train_17.csv',
 'datasets/housing/my_train_18.csv',
 'datasets/housing/my_train_19.csv']

In [ ]:
filepath_dataset =  tf.data.Dataset.list_files(train_filepaths, seed=42)

In [ ]:
for filepath in filepath_dataset:
  print(filepath)

tf.Tensor(b'datasets/housing/my_train_05.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_16.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_01.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_17.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_00.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_14.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_10.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_02.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_12.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_19.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_07.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_09.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_13.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_15.csv', shape=(), dtype=string)
tf.Ten

In [ ]:
n_readers = 5
dataset = filepath_dataset.interleave(
    lambda filepath: tf.data.TextLineDataset(filepath).skip(1),
    cycle_length=n_readers
)

In [ ]:
for line in dataset.take(5):
  print(line.numpy())

b'4.5909,16.0,5.475877192982456,1.0964912280701755,1357.0,2.9758771929824563,33.63,-117.71,2.418'
b'2.4792,24.0,3.4547038327526134,1.1341463414634145,2251.0,3.921602787456446,34.18,-118.38,2.0'
b'4.2708,45.0,5.121387283236994,0.953757225433526,492.0,2.8439306358381504,37.48,-122.19,2.67'
b'2.1856,41.0,3.7189873417721517,1.0658227848101265,803.0,2.0329113924050635,32.76,-117.12,1.205'
b'4.1812,52.0,5.701388888888889,0.9965277777777778,692.0,2.4027777777777777,33.73,-118.31,3.215'


13.1.3 데이터 전처리

In [ ]:
#x_mean, x_std = [...] 훈련 세트에 있는 각 특성의 평균과 표준 편차
n_inputs = 8

def preprocess(line):
  defs = [0.] * n_inputs + [tf.constant(
      [], dtype=tf.float32
  )]
  fields = tf.io.decode_csv(line, record_defaults=defs)
  x = tf.stack(fields[:-1])
  y = tf.stack(fields[-1:])
  return (x - x_mean) / x_std, y

In [ ]:
preprocess(b'4.2083,44.0, 5.3232, 0.9171,846.0, 2.3370,37.47, -122.2, 2.782')

(<tf.Tensor: shape=(8,), dtype=float32, numpy=
 array([ 0.16579159,  1.216324  , -0.05204564, -0.39215982, -0.5277444 ,
        -0.2633488 ,  0.8543046 , -1.3072058 ], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.782], dtype=float32)>)

13.1.4 데이터 적재와 전처리를 합치기

In [ ]:
def csv_reader_dataset(filepaths, repeat=1, n_readers=5, n_read_threads=None,
                       shuffle_buffer_size=10000, n_parse_threads=5, batch_size=32):
  dataset = tf.data.Dataset.list_files(filepaths).repeat(repeat)
  dataset = dataset.interleave(
      lambda filepath: tf.data.TextLineDataset(filepath).skip(1),
      cycle_length=n_readers, num_parallel_calls=n_read_threads
  )

  dataset = dataset.shuffle(shuffle_buffer_size)
  dataset = dataset.map(preprocess, num_parallel_calls=n_parse_threads)
  return dataset.batch(batch_size).prefetch(1)

In [ ]:
tf.random.set_seed(42)
train_set = csv_reader_dataset(train_filepaths, batch_size=3)
for x_batch, y_batch in train_set.take(2):
  print("x =", x_batch)
  print("y =", y_batch)
  print()

x = tf.Tensor(
[[ 0.5804519  -0.20762321  0.05616303 -0.15191229  0.01343246  0.00604472
   1.2525111  -1.3671792 ]
 [ 5.818099    1.8491895   1.1784915   0.28173092 -1.2496178  -0.3571987
   0.7231292  -1.0023477 ]
 [-0.9253566   0.5834586  -0.7807257  -0.28213993 -0.36530012  0.27389365
  -0.76194876  0.72684526]], shape=(3, 8), dtype=float32)
y = tf.Tensor(
[[1.752]
 [1.313]
 [1.535]], shape=(3, 1), dtype=float32)

x = tf.Tensor(
[[-0.8324941   0.6625668  -0.20741376 -0.18699841 -0.14536144  0.09635526
   0.9807942  -0.67250353]
 [-0.62183803  0.5834586  -0.19862501 -0.3500319  -1.1437552  -0.3363751
   1.107282   -0.8674123 ]
 [ 0.8683102   0.02970133  0.3427381  -0.29872298  0.7124906   0.28026953
  -0.72915536  0.86178064]], shape=(3, 8), dtype=float32)
y = tf.Tensor(
[[0.919]
 [1.028]
 [2.182]], shape=(3, 1), dtype=float32)



13.1.5 프리페치

13.1.6 tf.keras와 데이터셋 사용하기

In [ ]:
train_set = csv_reader_dataset(train_filepaths)
valid_set = csv_reader_dataset(valid_filepaths)
test_set = csv_reader_dataset(test_filepaths)

In [ ]:
keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)

In [ ]:
model = keras.models.Sequential([
  keras.layers.Dense(30, activation="relu", input_shape=x_train.shape[1:]),
  keras.layers.Dense(1)
])

In [ ]:
model.compile(loss="mse", optimizer=keras.optimizers.SGD(lr=1e-3))

In [ ]:
batch_size = 32
model.fit(train_set, epochs=10, validation_data=valid_set) #steps_per_epoch=len(x_train) // batch_size, 

Epoch 1/10
363/363 [==============================] - 1s 3ms/step - loss: 1.6391 - val_loss: 0.9463
Epoch 2/10
363/363 [==============================] - 1s 2ms/step - loss: 0.7066 - val_loss: 0.6542
Epoch 3/10
363/363 [==============================] - 1s 2ms/step - loss: 0.6346 - val_loss: 0.6065
Epoch 4/10
363/363 [==============================] - 1s 2ms/step - loss: 0.5977 - val_loss: 0.5705
Epoch 5/10
363/363 [==============================] - 1s 2ms/step - loss: 0.5701 - val_loss: 0.5420
Epoch 6/10
363/363 [==============================] - 1s 2ms/step - loss: 0.5477 - val_loss: 0.5275
Epoch 7/10
363/363 [==============================] - 1s 2ms/step - loss: 0.5294 - val_loss: 0.4944
Epoch 8/10
363/363 [==============================] - 1s 2ms/step - loss: 0.5130 - val_loss: 0.4850
Epoch 9/10
363/363 [==============================] - 1s 2ms/step - loss: 0.4997 - val_loss: 0.4670
Epoch 10/10
363/363 [==============================] - 1s 2ms/step - loss: 0.4879 - val_loss: 0.4587

In [ ]:
model.evaluate(test_set)
new_set = test_set.take(3).map(lambda X, y: X) #새로운 샘플이 3개 있다고 가정
model.predict(new_set)

162/162 [==============================] - 0s 2ms/step - loss: 0.4768


array([[1.8246477 ],
       [1.1649357 ],
       [1.7166657 ],
       [0.97491825],
       [2.4979835 ],
       [2.2972643 ],
       [1.7556832 ],
       [4.3428483 ],
       [2.060362  ],
       [2.3412867 ],
       [2.4690478 ],
       [2.961075  ],
       [2.7318287 ],
       [2.3811243 ],
       [1.1390718 ],
       [2.0844975 ],
       [3.519305  ],
       [2.28826   ],
       [4.907612  ],
       [1.7516866 ],
       [4.2348604 ],
       [1.2620912 ],
       [2.38176   ],
       [1.577371  ],
       [2.79051   ],
       [1.756511  ],
       [1.794009  ],
       [2.4247792 ],
       [3.114032  ],
       [1.5022981 ],
       [2.2059555 ],
       [1.3772786 ],
       [2.3967018 ],
       [1.5629871 ],
       [5.516988  ],
       [2.2404964 ],
       [1.8688171 ],
       [2.1682742 ],
       [1.3639779 ],
       [3.1941426 ],
       [1.1026578 ],
       [1.0875453 ],
       [3.9721904 ],
       [1.987387  ],
       [1.3666742 ],
       [2.9993486 ],
       [2.2836924 ],
       [1.050

In [ ]:
optimizer = keras.optimizers.Nadam(lr=0.01)
loss_fn = keras.losses.mean_squared_error
n_epochs = 5
batch_size = 32
n_steps_per_epoch = len(x_train) // batch_size
total_steps = n_epochs * n_steps_per_epoch
global_step = 0

#for x_batch, y_batch in train_set:
for x_batch, y_batch in train_set.take(total_steps):
  global_step += 1
  print("\n Global step {}/{}".format(global_step, total_steps), end="")
  with tf.GradientTape() as tape:
    y_pred = model(x_batch)
    main_loss = tf.reduce_mean(loss_fn(y_batch, y_pred))
    loss = tf.add_n(
        [main_loss] + model.losses
    )
  gradients = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(
      gradients, model.trainable_variables
  ))


 Global step 1/1810
 Global step 2/1810
 Global step 3/1810
 Global step 4/1810
 Global step 5/1810
 Global step 6/1810
 Global step 7/1810
 Global step 8/1810
 Global step 9/1810
 Global step 10/1810
 Global step 11/1810
 Global step 12/1810
 Global step 13/1810
 Global step 14/1810
 Global step 15/1810
 Global step 16/1810
 Global step 17/1810
 Global step 18/1810
 Global step 19/1810
 Global step 20/1810
 Global step 21/1810
 Global step 22/1810
 Global step 23/1810
 Global step 24/1810
 Global step 25/1810
 Global step 26/1810
 Global step 27/1810
 Global step 28/1810
 Global step 29/1810
 Global step 30/1810
 Global step 31/1810
 Global step 32/1810
 Global step 33/1810
 Global step 34/1810
 Global step 35/1810
 Global step 36/1810
 Global step 37/1810
 Global step 38/1810
 Global step 39/1810
 Global step 40/1810
 Global step 41/1810
 Global step 42/1810
 Global step 43/1810
 Global step 44/1810
 Global step 45/1810
 Global step 46/1810
 Global step 47/1810
 Global step 48/1810


In [ ]:
keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)


In [ ]:
optimizer = keras.optimizers.Nadam(lr=0.01)
loss_fn = keras.losses.mean_squared_error

@tf.function
def train(model, n_epochs, batch_size=32, n_readers=5, n_read_threads=5, shuffle_buffer_size=10000,
          n_parse_threads=5):
  train_set = csv_reader_dataset(train_filepaths, repeat=n_epochs, n_readers=n_reader, n_read_threads=n_read_threads, shuffle_buffer_size=shuffle_buffer_size,
                                 n_parse_threads=n_parse_threads, batch_size=batch_size)
  for x_batch, y_batch in train_set:
    with tf.GradientTape() as tape:
      y_pred = model(x_batch)
      main_loss = tf.reduce_mean(loss_fn(y_batch, y_pred))
      loss = tf.add_n(
          [main_loss] + model.losses
      )
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(
        zip(gradients, model.trainable_variables)
    )
  train(model, 5)

13.2 TFRecord 포맷

In [ ]:
with tf.io.TFRecordWriter("my_data.tfrecord") as f:
  f.write(b"This is the first record")
  f.write(b"And this is the second record")

In [ ]:
filepaths = ["my_data.tfrecord"]
dataset = tf.data.TFRecordDataset(filepaths)
for item in dataset:
  print(item)

tf.Tensor(b'This is the first record', shape=(), dtype=string)
tf.Tensor(b'And this is the second record', shape=(), dtype=string)


13.2.1 압축된 TFRecord 파일

In [ ]:
options = tf.io.TFRecordOptions(compression_type="GZIP")
with tf.io.TFRecordWriter("my_compressed.tfrecord", options) as f:
  f.write(b"This is the first record")
  f.write(b"And this is the second record")

In [ ]:
dataset = tf.data.TFRecordDataset(
    ["my_compressed.tfrecord"], compression_type="GZIP"
)

for item in dataset:
  print(item)

tf.Tensor(b'This is the first record', shape=(), dtype=string)
tf.Tensor(b'And this is the second record', shape=(), dtype=string)


13.2.2 프로토콜 버퍼 개요

In [ ]:
%%writefile person.proto

syntax = "proto3"
message Person {
    string name = 1;
    int32 id = 2;
    repeated string email = 3;
}

Overwriting person.proto


In [ ]:
!protoc person.proto --python_out=. --descriptor_set_out=person.desc --include_imports

person.proto:3:1: Expected ";".


In [ ]:
!ls person*

person.desc  person_pb2.py  person.proto


In [ ]:
from person_pb2 import Person #생성된 클래스 임포트
person = Person(name="Al", id=123, email=["a@b.com"]) #객체 생성
print(person)

name: "Al"
id: 123
email: "a@b.com"



In [ ]:
person.name

'Al'

In [ ]:
person.email[0]

'a@b.com'

In [ ]:
person.email.append("c@d.com")

In [ ]:
s = person.SerializeToString()

In [ ]:
s


b'\n\x05Alice\x10{\x1a\x07a@b.com\x1a\x07c@d.com\x1a\x07c@d.com'

In [ ]:
person2 = Person()

In [ ]:
person2.ParseFromString(s)

36

In [ ]:
person == person2

True

In [ ]:
person.name = "Alice"

13.2.3 텐서플로 프로토콜 버퍼

In [ ]:
# The following functions can be used to convert a value to a type compatible
# with tf.Example.

def _bytes_feature(value):
    """Returns a bytes_list from a string / byte."""
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _float_feature(value):
    """Returns a float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def _int64_feature(value):
    """Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

In [ ]:
%%writefile Feature.proto

syntax = "proto3";

message BytesList { repeated bytes value = 1; }
message FloatList { repeated float value = 1 [packed = true]; }
message Int64List { repeated int64 value = 1 [packed = true]; }
message Feature {
    oneof kind {
        BytesList bytes_list = 1;
        FloatList float_list = 2;
        Int64List int64_list = 3;
    }
};
message Features { map<string, Feature> feature = 1; };
message Example { Featrues features };

Overwriting Feature.proto


In [ ]:
#from tensorflow.train import BytesList, FloatList, Int64List
#from tensorflow.train import Feature, Features, Example

BytesList = tf.train.BytesList
FloatList = tf.train.FloatList
Int64List = tf.train.Int64List
Feature = tf.train.Feature
Features = tf.train.Features
Example = tf.train.Example

person_example = Example(
    features = Features(
        feature={
            "name": Feature(bytes_list=BytesList(value=[b"Alice"])),
            "id": Feature(int64_list=Int64List(value=[123])),
            "emails": Feature(bytes_list=BytesList(value=[b"a@b.com", b"c@d.com"]))
        }
    )
)

In [ ]:
with tf.io.TFRecordWriter("my_contacts.tfrecord") as f:
  f.write(person_example.SerializeToString())

13.2.3 Example 프로토콜 버퍼를 읽고 파싱하기

In [ ]:
feature_description = {
    "name": tf.io.FixedLenFeature(
        [], tf.string, default_value=""
    ),
    "id": tf.io.FixedLenFeature(
        [], tf.int64, default_value=0
    ),
    "emails": tf.io.VarLenFeature(tf.string)
}

for serialized_example in tf.data.TFRecordDataset(["my_contacts.tfrecord"]):
  parsed_example = tf.io.parse_single_example(serialized_example, feature_description)

In [ ]:
tf.sparse.to_dense(
    parsed_example["emails"], default_value=b""
)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'a@b.com', b'c@d.com'], dtype=object)>

In [ ]:
parsed_example["emails"].values

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'a@b.com', b'c@d.com'], dtype=object)>

In [ ]:
dataset = tf.data.TFRecordDataset(["my_contacts.tfrecord"]).batch(10)
for serialized_example in dataset:
  parsed_examples = tf.io.parse_example(serialized_example, feature_description)

13.2.4 SequenceExample 프로토콜 버퍼를 사용해 리스트의 리스트 다루기

In [ ]:
%%writefile Sequence.proto

syntax = "proto3";

message FeatureList { repeated Feature feature = 1; };
message FeatureLists { map<string, FeatureList> feature_list = 1; };
message SequenceExample {
    Feature context = 1;
    FeatureLists feature_lists = 2;
};

Overwriting Sequence.proto


In [ ]:
parsed_examples

{'emails': <tensorflow.python.framework.sparse_tensor.SparseTensor at 0x7fce2757f4e0>,
 'id': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([123])>,
 'name': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Alice'], dtype=object)>}

In [ ]:
serialized_sequence_example = sequence_example.SerializeToString()

In [ ]:

#from tensorflow.train import FeatureList, FeatureLists, SequenceExample
FeatureList = tf.train.FeatureList
FeatureLists = tf.train.FeatureLists
SequenceExample = tf.train.SequenceExample

context_feature_descriptions = {
    "author_id": tf.io.FixedLenFeature(
        [], tf.int64, default_value = 0
    ),
    "title": tf.io.VarLenFeature(tf.string),
    "pub_date": tf.io.FixedLenFeature(
        [3], tf.int64, default_value=[0,0,0]
    )
}

sequence_feature_descriptions = {
    "content": tf.io.VarLenFeature(tf.string),
    "comments": tf.io.VarLenFeature(tf.string)
}

In [ ]:
parsed_context, parsed_feature_lists = tf.io.parse_single_sequence_example(
    serialized_sequence_example, context_feature_descriptions, sequence_feature_descriptions
)

parsed_content = tf.RaggedTensor.from_sparse(parsed_feature_lists["content"])

13.3 입력 특성 전처리

In [ ]:
means = np.mean(x_train, axis=0, keepdims=True)
stds = np.std(x_train, axis=0, keepdims=True)
eps = keras.backend.epsilon()
model = keras.models.Sequential(
    [
     keras.layers.Lambda(lambda inputs: (inputs - means) / (stds + eps)),
     #[...] #다른 층
    ]
)

In [ ]:
keras.backend.clear_session()

In [ ]:
tf.random.set_seed(42)
np.random.seed(42)

In [ ]:
class Standardzation(keras.layers.Layer):
  def adapt(self, data_sample):
    self.means_ = np.mean(data_sample, axis=0, keepdims=True)
    self.stds_ = np.std(data_sample, axis=0, keepdims=True)
  def call(self, inputs):
    return (inputs - self.means_) / (self.stds_ + keras.backend.epsilon())

In [ ]:
std_layer = Standardzation()
#std_layer.adapt(data_sample)

In [ ]:
model = keras.Sequential()

In [ ]:
model.add(std_layer)

In [ ]:
#모델 구성
#model.compile([...])
#model.fit([...])

13.3.1 원-핫 벡터를 사용해 범주형 특성 인코딩하기

In [ ]:
vocab = ["<1H OCEAN", "INLAND", "NEAR OCEAN", "NEAR BAY", "ISLAND"]
indices = tf.range(
    len(vocab), dtype=tf.int64
)
table_init = tf.lookup.KeyValueTensorInitializer(vocab, indices)
num_oov_buckets = 2
table = tf.lookup.StaticVocabularyTable(table_init, num_oov_buckets)

In [ ]:
categories = tf.constant(
    ["NEAR BAY", "DESERT", "INLAND", "INLAND"]
)
cat_indices = table.lookup(categories)
cat_indices

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 5, 1, 1])>

In [ ]:
cat_one_hot = tf.one_hot(cat_indices, depth=len(vocab) + num_oov_buckets)
cat_one_hot

<tf.Tensor: shape=(4, 7), dtype=float32, numpy=
array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>

13.3.2 임베딩을 사용해 범주형 특성 인코딩하기

In [ ]:
embedding_dim = 2
embed_init = tf.random.uniform(
    [
     len(vocab) + num_oov_buckets, embedding_dim
    ]
)
embedding_metrix = tf.Variable(embed_init)

In [ ]:
embedding_metrix

<tf.Variable 'Variable:0' shape=(7, 2) dtype=float32, numpy=
array([[0.6645621 , 0.44100678],
       [0.3528825 , 0.46448255],
       [0.03366041, 0.68467236],
       [0.74011743, 0.8724445 ],
       [0.22632635, 0.22319686],
       [0.3103881 , 0.7223358 ],
       [0.13318717, 0.5480639 ]], dtype=float32)>

In [ ]:
categories = tf.constant(
    ["NEAR BAY", "DESERT", "INLAND", "INLAND"]
)
cat_indices = table.lookup(categories)
cat_indices

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 5, 1, 1])>

In [ ]:
tf.nn.embedding_lookup(embedding_metrix, cat_indices)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.74011743, 0.8724445 ],
       [0.3103881 , 0.7223358 ],
       [0.3528825 , 0.46448255],
       [0.3528825 , 0.46448255]], dtype=float32)>

In [ ]:
embedding = keras.layers.Embedding(
    input_dim=len(vocab) + num_oov_buckets, output_dim=embedding_dim
)

embedding(cat_indices)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.04467482,  0.02493341],
       [-0.02383961,  0.01973433],
       [ 0.04309944, -0.0247813 ],
       [ 0.04309944, -0.0247813 ]], dtype=float32)>

In [ ]:
regular_inputs = keras.layers.Input(shape=[8])
categories = keras.layers.Input(shape=[], dtype=tf.string)

cat_indices = keras.layers.Lambda( lambda cats: table.lookup(cats) )(categories)
cat_embed = keras.layers.Embedding(input_dim=6, output_dim=2)(cat_indices)
encoded_inputs = keras.layers.concatenate(
    [regular_inputs, cat_embed]
)
outputs = keras.layers.Dense(1)(encoded_inputs)
model = keras.models.Model(inputs=[regular_inputs, categories], outputs=[outputs])

13.3.3 케라스 전처리 층

In [ ]:
#normalization = keras.layers.Normalization()
#discretization = keras.layers.Discretization([...])
##pipeline = keras.layers.PreprocessingStage(
#    [normalization, discretization]
#)
#pipeline.adapt(data_sample)

13.4 TF 변환

In [ ]:
try:
  import tensorflow_transform as tft

  def preprocess(inputs):
    median_age = inputs["housing_median_age"]
    ocean_proximity = inputs["ocean_proximity"]
    standardized_age = tft.scale_to_z_score(median_age)
    ocean_proximity_id = tft.compute_and_apply_vocabulary(ocean_proximity)
    return {
        "standardized_median_age": standardized_age,
        "ocean_proximity_id": ocean_proximity_id
    }
except ImportError:
  print("TF transform is not installed try running : pip install -U tensorflow-transform")

In [ ]:
pip install tensorflow-transform

     |████████████████████████████████| 389kB 5.5MB/s 
     |████████████████████████████████| 8.7MB 18.6MB/s 
     |████████████████████████████████| 2.2MB 39.5MB/s 
     |████████████████████████████████| 829kB 34.7MB/s 
     |████████████████████████████████| 61kB 5.8MB/s 
     |████████████████████████████████| 63.8MB 66kB/s 
     |████████████████████████████████| 2.0MB 38.1MB/s 
     |████████████████████████████████| 51kB 6.1MB/s 
     |████████████████████████████████| 153kB 43.2MB/s 
     |████████████████████████████████| 61kB 7.3MB/s 
     |████████████████████████████████| 92kB 9.9MB/s 
     |████████████████████████████████| 122kB 35.7MB/s 
     |████████████████████████████████| 256kB 39.9MB/s 
     |████████████████████████████████| 174kB 45.3MB/s 
     |████████████████████████████████| 440kB 43.3MB/s 
     |████████████████████████████████| 174kB 48.9MB/s 
     |████████████████████████████████| 153kB 42.5MB/s 
     |████████████████████████████████| 184kB 44.3MB/s 
  

13.5 텐서플로 데이터셋(TFDS) 프로젝트

In [ ]:
import tensorflow_datasets as tfds

dataset = tfds.load(name="mnist")
mnist_train, mnist_test = dataset["train"], dataset["test"]

local data directory. If you'd instead prefer to read directly from our public
GCS bucket (recommended if you're running on GCP), you can instead pass
`try_gcs=True` to `tfds.load` or set `data_dir=gs://tfds-data/datasets`.





Dataset mnist downloaded and prepared to /root/tensorflow_datasets/mnist/3.0.1. Subsequent calls will reuse this data.


In [ ]:
mnist_train = mnist_train.shuffle(10000).batch(32)
mnist_train = mnist_train.map(lambda items: (
    item["image"], items["label"]
))
mnist_train = mnist_train.prefetch(1)
#for item in mnist_train:
#  images = item["image"]
#  labels = item["label"]
#  for idx in range(5):
#    plt.subplot(1, 5, idx + 1)
#    image = images[idx, ..., 0]
#    label = labels[idx].numpy()
    #plt.imshow(image, cmap="binary")
#    plt.title(label)
##    plt.axis("off")
#  break

In [ ]:
dataset = tfds.load(name="mnist", batch_size=32, as_supervised=True)
mnist_train = dataset["train"].prefetch(1)
#model = keras.models.Sequential([...])
model.compile(loss="sparse_categorical_crossentropy", optimizer="sgd")
#model.fit(mnist_train, epochs=5)

Epoch 1/5


AssertionError: ignored